# Generated by Django 4.2.6 on 2023-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='')),
                ('Father_Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Aadhar', models.BigIntegerField()),
                ('Doj', models.DateField()),
                ('Education', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('Office_Address', models.CharField(max_length=100)),
                ('Phone_no', models.BigIntegerField()),
                ('Monthly_Rent', models.IntegerField()),
                ('Deposit', models.IntegerField()),
                ('Maintain_Charge', models.IntegerField()),
            ],
        ),
    ]
