# Generated by Django 4.2.6 on 2024-01-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_floor_room_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
