# Generated by Django 4.2.6 on 2024-01-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_floor_room_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='room',
            new_name='user_room',
        ),
    ]
