# Generated by Django 4.2.6 on 2024-01-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_room_complaints_user_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='user_room',
            new_name='room',
        ),
    ]
