# Generated by Django 4.2.6 on 2024-01-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_user_room_complaints_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='room',
            new_name='user_room',
        ),
    ]
